giocatori:
  - nome: "De Gea"
    squadra: "Fiorentina"
    ruolo: P
  - nome: "Mandas"
    squadra: "Lazio"
    ruolo: P
  - nome: "Okoye"
    squadra: "Udinese"
    ruolo: P

  - nome: "Dimarco"
    squadra: "Inter"
    ruolo: D
  - nome: "Kalulu"
    squadra: "Juventus"
    ruolo: D
  - nome: "Spence"
    squadra: "Inter"
    ruolo: D
  - nome: "Spinazzola"
    squadra: "Napoli"
    ruolo: D
  - nome: "Akanji"
    squadra: "Inter"
    ruolo: D
  - nome: "Scalvini"
    squadra: "Atalanta"
    ruolo: D
  - nome: "Stones"
    squadra: "Inter"
    ruolo: D
  - nome: "Miranda J."
    squadra: "Bologna"
    ruolo: D

  - nome: "McTominay"
    squadra: "Napoli"
    ruolo: C
  - nome: "Orsolini"
    squadra: "Bologna"
    ruolo: C
  - nome: "Fabbian"
    squadra: "Parma"
    ruolo: C
  - nome: "Cancellieri"
    squadra: "Lazio"
    ruolo: C
  - nome: "Ferguson"
    squadra: "Bologna"
    ruolo: C
  - nome: "Thuram K."
    squadra: "Juventus"
    ruolo: C
  - nome: "Perez K."
    squadra: "Venezia"
    ruolo: C
  - nome: "Zambo Anguissa"
    squadra: "Napoli"
    ruolo: C

  - nome: "Kean"
    squadra: "Como"
    ruolo: A
  - nome: "Geubbels"
    squadra: "Lecce"
    ruolo: A
  - nome: "Krstovic"
    squadra: "Atalanta"
    ruolo: A
  - nome: "Woltemade"
    squadra: "Juventus"
    ruolo: A
  - nome: "Adams A."
    squadra: "Venezia"
    ruolo: A
  - nome: "Touré E."
    squadra: "Parma"
    ruolo: A
